version: "3"

networks:
  hadoop-spark-net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

services:
  datanode4:
    image: hadoop-spark:latest
    container_name: datanode4
    hostname: datanode4
    command: /usr/local/hadoop/bin/hdfs datanode
    ports:
      - "9866:9866"
      - "7077:7077"
      - "9000:9000"
    volumes:
      - ./data/datanode4:/usr/local/hadoop/hadoop_data/hdfs/datanode
    environment:
      - CONTAINER_NAMES=namenode datanode1 datanode2 datanode3 datanode4
    networks:
      hadoop-spark-net:
        ipv4_address: 172.28.0.6
